# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'PhotoApp_CK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for PhotoApp_CK
  pod "ComponentKit"

end
