// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from photoapp.djinni

#import <Foundation/Foundation.h>
@class PAPhotoapp;


@interface PAPhotoapp : NSObject

+ (nullable PAPhotoapp *)create;

- (nonnull NSString *)getPhotoapp;

@end
