// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from photoapp.djinni

#include "photoapp.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PAPhotoapp;

namespace djinni_generated {

class Photoapp
{
public:
    using CppType = std::shared_ptr<::photoapp::Photoapp>;
    using CppOptType = std::shared_ptr<::photoapp::Photoapp>;
    using ObjcType = PAPhotoapp*;

    using Boxed = Photoapp;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

