// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from photoapp.djinni

#import "PAPhotoapp+Private.h"
#import "PAPhotoapp.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PAPhotoapp ()

- (id)initWithCpp:(const std::shared_ptr<::photoapp::Photoapp>&)cppRef;

@end

@implementation PAPhotoapp {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::photoapp::Photoapp>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::photoapp::Photoapp>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable PAPhotoapp *)create {
    try {
        auto objcpp_result_ = ::photoapp::Photoapp::create();
        return ::djinni_generated::Photoapp::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getPhotoapp {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_photoapp();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Photoapp::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Photoapp::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PAPhotoapp>(cpp);
}

}  // namespace djinni_generated

@end
