language: objective-c
osx_image: xcode9.2

install:
  - gem install xcpretty -N --no-ri --no-rdoc

script:
  - ./build.sh $BUILD_SUBCOMMAND

env:
  matrix:
    - BUILD_SUBCOMMAND="ci-componentkit-ios"
    - BUILD_SUBCOMMAND="ci-componentkit-tvos"
    - BUILD_SUBCOMMAND="ci-wildeguess-ios"
